### ISSUE TITLE
Sprint does not properly sort winners

### ISSUE THREAD

**Issue by JustHereToReportABug** [cwarwicker/discord-WriterBot#10]
https://github.com/cwarwicker/discord-WriterBot/blob/ad8aefd6ef3fd5b4d4c410d8c1ccc11e8561ecb5/commands/writing/sprint.js#L993

I forked writer bot a while ago for my writing server, but you are no longer in that server and haven't accepted my friend request, so I figured I'd report this bug here so at least you are aware of it for your own server.

Line #993 of sprint.js is currently
`return a.count < b.count;`
but it should be 
`return b.count - a.count;`

The bug is that if you have users who sprint with a starting word count greater than zero, the results table of the sprint won't sort them correctly.  Instead of sorting them by words written it sorts them by total word count, including what they started with  

This bug is fixed by using a subtraction sort function instead of a less-than sort function.  You can see an example of why this is the case here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#Creating_displaying_and_sorting_an_array  In general, using a subtraction function is the preferred method for sorting an array (although TBH I did not know that until I looked into it).

I also was able to repeatedly replicate (and fix) this bug not only with users on my actual writing server, but with multiple test-accounts on my development server.

Anyway, really love writer-bot and it's been great and very extensible because of the use of discord.js, commando, and sqlite.  Thanks!

**Comment by cwarwicker** [comment]
Thanks, i've fixed this now.
